#!/usr/bin/env bash

dry="0"
while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "executing: $@"
    if [[ $dry == "0" ]]; then
        "$@"
    fi
}


round=0
while [[ true ]]; do
    round=$(($round + 1))
    answer="n"
    read -p "Are you ready (y/n)?" answer

    if [[ $answer != "y" ]]; then
        exit 0
    fi


    sudo log "round $round"
    log "waiting for a submit ..."
    log "also don't get it wrong..."

    if ./leet.js listen; then
        log "great success, looks like you live another day"
        
    else
        log "you have failed me for the last time"
        log "goodbye"
    fi
done
